### ISSUE TITLE
Move under `Coreproject` organization 

### ISSUE THREAD

**Issue by baseplate-admin** [coreproject-moe/frontend#705]
We will use main domain for vercel deployment

cons:
- You will lose access to `v3.coreproject.moe`  domain and vercel deployment in this repo

**Comment by tokitou-san** [comment]
IMHO I dont think we need this migration now.
also build time on netlify is far lesser than vercel. ya know right?
So for now I think keep this frontend here and keep this issue open, lets see if anyone has any opinion about this migration.
Whadya think?

**Comment by baseplate-admin** [comment]
Nice work
